framework:
    rate_limiter:
        # example for custom rate-limit:
        auth_token_authentication:
            policy: 'sliding_window'
            limit: 10
            interval: '60 minutes'
        anonymous_api_common:
            policy: 'sliding_window'
            limit: 1000
            interval: '60 minutes'
        authenticated_api_common:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }
