version: "3.7"

services:
  nginx:
    ports:
      - "8079:80"

  app-postgres-db:
    ports:
      - "54321:5432"

  rabbitmq:
    ports:
      - "5671:5672"
      - "15671:15672"

  prometheus:
    ports:
      - "9091:9090"

  grafana:
    ports:
      - "3001:3000"
