sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
    options:
        traces_sample_rate: 1.0
        profiles_sample_rate: 1.0
    tracing:
        enabled: true
        dbal: # DB queries
          enabled: true
        cache: # cache pools
          enabled: true
        twig: # templating engine
          enabled: true
        http_client: # Symfony HTTP client
          enabled: true

monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
